// <auto-generated />
namespace GraduateDesignBk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 为问题增加标题和描述赞和评论数目 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(为问题增加标题和描述赞和评论数目));
        
        string IMigrationMetadata.Id
        {
            get { return "201602050547308_为问题增加标题和描述赞和评论数目"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
