// <auto-generated />
namespace GraduateDesignBk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 重新名义下名称并且增加公告表 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(重新名义下名称并且增加公告表));
        
        string IMigrationMetadata.Id
        {
            get { return "201602221331125_重新名义下名称并且增加公告表"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
