// <auto-generated />
namespace GraduateDesignBk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 增加一个只能给问题点赞一次的表 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(增加一个只能给问题点赞一次的表));
        
        string IMigrationMetadata.Id
        {
            get { return "201602050724155_增加一个只能给问题点赞一次的表"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
