// <auto-generated />
namespace GraduateDesignBk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 改变了外键关联关系1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(改变了外键关联关系1));
        
        string IMigrationMetadata.Id
        {
            get { return "201602270616191_改变了外键关联关系1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
