// <auto-generated />
namespace GraduateDesignBk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 去掉问题的评论数 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(去掉问题的评论数));
        
        string IMigrationMetadata.Id
        {
            get { return "201602050553160_去掉问题的评论数"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
