// <auto-generated />
namespace GraduateDesignBk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 删除了文件的外键用户id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(删除了文件的外键用户id));
        
        string IMigrationMetadata.Id
        {
            get { return "201602270722580_删除了文件的外键用户id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
