// <auto-generated />
namespace GraduateDesignBk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 给公告加上置顶 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(给公告加上置顶));
        
        string IMigrationMetadata.Id
        {
            get { return "201602231430431_给公告加上置顶"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
