// <auto-generated />
namespace GraduateDesignBk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 将问题表和评论表分开成两个表 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(将问题表和评论表分开成两个表));
        
        string IMigrationMetadata.Id
        {
            get { return "201602110739484_将问题表和评论表分开成两个表"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
